// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqvw_HCS_DwubAKjq-8-cquWpIHSDh7eI',
    appId: '1:38263915997:web:9c2d50b5768400d47a2234',
    messagingSenderId: '38263915997',
    projectId: 'fenmeeting-app-ad4fa',
    authDomain: 'fenmeeting-app-ad4fa.firebaseapp.com',
    storageBucket: 'fenmeeting-app-ad4fa.appspot.com',
    measurementId: 'G-EGXEXNMD2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1EsS8uAKQsgH2ZxVXCoGhHYtZDsQYEJI',
    appId: '1:38263915997:android:587fde7ea0e7e21a7a2234',
    messagingSenderId: '38263915997',
    projectId: 'fenmeeting-app-ad4fa',
    storageBucket: 'fenmeeting-app-ad4fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxnBopwWd25D4yC4dgsPGoWokbV9gejz0',
    appId: '1:38263915997:ios:510ae68603baaa3f7a2234',
    messagingSenderId: '38263915997',
    projectId: 'fenmeeting-app-ad4fa',
    storageBucket: 'fenmeeting-app-ad4fa.appspot.com',
    iosClientId: '38263915997-9u83k5b8ffiag19pm6d4i82434t8lmb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fencingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxnBopwWd25D4yC4dgsPGoWokbV9gejz0',
    appId: '1:38263915997:ios:642ea7ad340ae9587a2234',
    messagingSenderId: '38263915997',
    projectId: 'fenmeeting-app-ad4fa',
    storageBucket: 'fenmeeting-app-ad4fa.appspot.com',
    iosClientId: '38263915997-19asc9fncs59tge0dupk4s0hrqu0m2us.apps.googleusercontent.com',
    iosBundleId: 'com.example.fencingApp.RunnerTests',
  );
}
