// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26RgDkuSl5rESmuID5uFFUMJtbrAgmj0',
    appId: '1:423740453518:web:807b56f42632674e6d4fdf',
    messagingSenderId: '423740453518',
    projectId: 'fenmeeting-app-8a3e0',
    authDomain: 'fenmeeting-app-8a3e0.firebaseapp.com',
    storageBucket: 'fenmeeting-app-8a3e0.appspot.com',
    measurementId: 'G-CC7QKERJ8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2vXDlPjsfKJs-Aan0m_7gs3UyIvJMxs',
    appId: '1:423740453518:android:64a7a922e2459f3c6d4fdf',
    messagingSenderId: '423740453518',
    projectId: 'fenmeeting-app-8a3e0',
    storageBucket: 'fenmeeting-app-8a3e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9fRC-ndRnfDI_FgN6m8a3cvtJQaXQCY',
    appId: '1:423740453518:ios:4810ffc3f755bef16d4fdf',
    messagingSenderId: '423740453518',
    projectId: 'fenmeeting-app-8a3e0',
    storageBucket: 'fenmeeting-app-8a3e0.appspot.com',
    iosClientId: '423740453518-fjo0h9nni1s9r8ocrrirolsfn94nol03.apps.googleusercontent.com',
    iosBundleId: 'com.example.fencingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd9fRC-ndRnfDI_FgN6m8a3cvtJQaXQCY',
    appId: '1:423740453518:ios:3d235aa8cd41547e6d4fdf',
    messagingSenderId: '423740453518',
    projectId: 'fenmeeting-app-8a3e0',
    storageBucket: 'fenmeeting-app-8a3e0.appspot.com',
    iosClientId: '423740453518-0dthc9emv3bqvi1oep3bkqkrsc2seens.apps.googleusercontent.com',
    iosBundleId: 'com.example.fencingApp.RunnerTests',
  );
}
